title = "Qualmand Driven's Blog"
baseURL = "https://qualmanddriven.github.io/"
languageCode = "en-us"
theme= "hyde"

[params]
    disqusShortname = "spf13"
    description = "Blogging about all kind of thoughts and mainly for C# programming language."